"area: adapters":
  - changed-files:
      - any-glob-to-any-file:
          - tornadoapi_guard/adapters.py

"area: integrations":
  - changed-files:
      - any-glob-to-any-file:
          - tornadoapi_guard/__init__.py

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**

examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - mkdocs.yml
          - README.md
          - CHANGELOG.md
          - CONTRIBUTING.md
          - SECURITY.md
          - CODE_OF_CONDUCT.md
          - LICENSE

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - .pre-commit-config.yaml

build:
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - Dockerfile
          - compose.yml
          - setup.py
          - vulture_whitelist.py

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pyproject.toml
          - uv.lock
