name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'compose.yml'
      - 'data/**'
      - 'Dockerfile'
      - 'examples/**'
      - 'tornadoapi_guard/**'
      - 'mypy.ini'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'pytest.ini'
      - 'setup.py'
      - 'tests/**'
  pull_request_target:
    branches:
      - master
    paths:
      - 'compose.yml'
      - 'data/**'
      - 'Dockerfile'
      - 'examples/**'
      - 'tornadoapi_guard/**'
      - 'mypy.ini'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'pytest.ini'
      - 'setup.py'
      - 'tests/**'
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - run: pip install uv
      - run: uv sync --extra dev
      - run: uv run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    permissions:
      pull-requests: write

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Run tests
        run: |
          IPINFO_TOKEN='${{ secrets.IPINFO_TOKEN }}' REDIS_URL='redis://localhost:6379' REDIS_PREFIX='test:tornadoapi_guard:' uv run pytest -v --cov=tornadoapi_guard
